# Generated by Django 2.2 on 2019-05-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_release_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
    ]
