# Generated by Django 2.2 on 2019-05-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
